[package]
name = "letsql"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "letsql"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.24", features = ["macros", "rt", "rt-multi-thread", "sync"] }
pyo3 = { version = "0.20", features = ["extension-module", "abi3", "abi3-py38"] }
datafusion = "=36.0.0"
datafusion-common = { version = "=36.0.0", features = ["pyarrow"] }
datafusion-expr = "=36.0.0"
prost = "=0.12"
prost-types = "=0.12"
datafusion-optimizer = "36.0.0"
datafusion-sql = "36.0.0"
futures = "0.3"
async-trait = "0.1"
arrow = "50.0.0"
gbdt = { git = "https://github.com/mesejo/gbdt-rs.git", branch = "feat/add-feature-mapping" }
parking_lot = { version = "0.12" }
