[project]
name = "letsql"
version = "0.1.1"
description = "Machine Learning pipelines with a familiar DataFrame and SQL UI "
authors = ["Daniel Mesejo <mesejoleon@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.9.*"
pip = "23.3.1.*"
